# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Если су объекта есть названеи (станция)', max_length=200, null=True, verbose_name='Название станции')),
                ('adres', models.CharField(blank=True, max_length=200, null=True)),
                ('geo_point', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('note', models.CharField(blank=True, max_length=500, null=True)),
                ('to_Place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='places', to='places.Places', verbose_name='Относится к станции')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Обьекты',
            },
        ),
    ]
