# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-13 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('work_profiles', '0002_auto_20171114_1556'),
        ('main_requests', '0008_auto_20180303_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата ввода')),
                ('start_datetime', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Начало работ')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Окончание работ')),
                ('works', models.CharField(help_text='Выполненные работы', max_length=1000)),
                ('about', models.CharField(blank=True, help_text='Максимальная дллина 1000 символов', max_length=1000, null=True, verbose_name='Дополнительная информация')),
                ('execute_users', models.ManyToManyField(help_text='Принимали участие в работе', related_name='departure_execute_users', to='work_profiles.Profile', verbose_name='Исполнители')),
                ('input_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Departure_input_user', to='work_profiles.Profile', verbose_name='Ввел')),
                ('main_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main_requests.MainRequest', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Выезд оснновной заявки',
                'verbose_name_plural': 'Выезды',
            },
        ),
    ]
