# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-27 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departure',
            name='main_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_requests.MainRequest', verbose_name='Заявка'),
        ),
    ]
