# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('work_profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('input_datetime', models.DateTimeField(auto_now_add=True)),
                ('request_dateTime', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('request_outer_User', models.CharField(blank=True, max_length=100, null=True)),
                ('about', models.TextField(max_length=1000)),
                ('receive_dateTime', models.DateTimeField(blank=True, null=True)),
                ('close_dateTime', models.DateTimeField(blank=True, null=True)),
                ('close_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mainRequestClose', to='work_profiles.Profile')),
                ('input_user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='mainRequestInput', to='work_profiles.Profile')),
                ('receive_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mainRequestReceive', to='work_profiles.Profile')),
                ('request_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mainRequestRequest', to='work_profiles.Profile')),
            ],
        ),
    ]
