# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainrequest',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
