# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_requests', '0002_auto_20171111_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainrequest',
            name='close_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mainRequestClose', to='work_profiles.Profile'),
        ),
    ]
