# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_requests', '0003_auto_20171113_1306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainrequest',
            options={'verbose_name': 'Главная заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AddField(
            model_name='mainrequest',
            name='place_outer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mainrequest',
            name='close_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mainRequestClose', to='work_profiles.Profile'),
        ),
    ]
