# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
        ('main_requests', '0005_auto_20171114_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainrequest',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_requests_places', to='places.Places'),
        ),
    ]
