# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_requests', '0006_mainrequest_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainrequest',
            name='request_outer_department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mainrequest',
            name='request_outer_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
