# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-17 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_requests', '0008_auto_20180303_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainrequest',
            name='changed_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
