# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-02 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_requests', '0009_mainrequest_changed_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainrequest',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main_requests_places', to='places.Places'),
        ),
    ]
