# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-27 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_profiles', '0002_auto_20171114_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='deparment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.department'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_position',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
